---
- name: Restarting mautic instance
  docker_compose:
    project_src: "{{ xayma_mautic_paths.instance }}"
    state: present
    restarted: true
  when: instancename != xayma_mautic.instancename # We make sure the user has provided an instance name
  