---
- name: Stoping mautic instance
  docker_compose:
    project_src: "{{ xayma_mautic_paths.instance }}"
    state: absent
  when: instancename != xayma_mautic.instancename # We make sure the user has provided an instance name
